export const dummyIncidentQueries = [
  'database issue after deployment',
  'postgres timeout after release',
  'redis cache instability',
  'payment gateway unavailable',
  'authentication service outage',
  'invoice generation problem',
  'kubernetes deployment failed',
  'high memory consumption detected',
  'api gateway latency spike',
  'nginx upstream unavailable',
  'storage bucket access issue',
  'kafka consumer lag incident',
  'email delivery degradation',
  'message queue congestion',
  'service restart loop detected',
  'database migration rollback',
  'payment reconciliation problem',
  'authentication token expiration issue',
  'high cpu usage on production node',
  'deployment caused service outage',
];